language: zephir
php:
- 5.4
- 5.5
- hhvm

env:
  global:
    - ES_VER=1.1.1
    - ES_MAPPER_ATTACHMENTS_VER=2.0.0.RC1
    - ES_TRANSPORT_THRIFT_VER=2.0.0.RC2
    - ES_GEOCLUSTER_FACET_VER=0.0.10
    - ES_WAIT_ON_MAPPING_CHANGE=true
    - MEMCACHE_VER=3.0.8
    - JSON_C_VER=0.12
    - ZEPHIR_VER=0.4.1
    - ZEPHIRDIR=/usr/local/src/zephir
  matrix:
    - ES_REQUIRE=dev
    - ES_REQUIRE=no-dev

services:
  - memcached

before_script:
  - ./unit-tests/ci/install_json-c.sh
  - ./unit-tests/ci/install_zephir.sh
  - sudo zephir build
  - (cd ext; export CFLAGS="-g3 -O1 -std=gnu90 -Wall"; phpize && ./configure --enable-elastica && make --silent -j4 && sudo make --silent install && phpenv config-add ../unit-tests/ci/shell.ini)

after_script:
  - ./unit-tests/ci/show_logs.sh
