language: php
php:
- 5.4
- 5.5
- 5.6
- hhvm

env:
  global:
    - SH_VER=dev
    - JSON_C_VER=0.12
    - ZEPHIR_VER=0.5.0
    - ZEPHIRDIR=/usr/local/src/zephir

before_script:
  - ./unit-tests/ci/install_json-c.sh
  - ./unit-tests/ci/install_zephir.sh
  - sudo zephir build
  - (cd ext; export CFLAGS="-g3 -O1 -std=gnu90 -Wall"; phpize && ./configure --enable-shell && make --silent -j4 && sudo make --silent install && phpenv config-add ../unit-tests/ci/shell.ini)

after_script:
  - ./unit-tests/ci/show_logs.sh
