language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6

env:
  global:
    - SH_VER=dev
    - JSON_C_VER=0.12
    - ZEPHIR_VER=0.5.0
    - ZEPHIRDIR=/usr/local/src/zephir

before_script:
  - ./unit-tests/ci/install_zephir.sh
  - zephir generate
  - cd ext && phpize && ./configure && make && sudo make install && phpenv config-add ../unit-tests/ci/shell.ini && cd ../

script:
  - php ./unit-tests/ci/test.php

after_failure:
  - php -m
  - php --info
